### ISSUE TITLE
Episode 4: collective communication

### ISSUE THREAD

**Issue by robertodr** [ENCCS/intermediate-mpi#21]
- Collective operations with user-defined datatypes (basically how to define own `MPI_Op`s)
- Exercise: ?

**Comment by mabraham** [comment]
I haven't added any content with user defined ops. I'll mention them as I present. But otherwise that sounds like reasonable advanced content?

**Comment by robertodr** [comment]
Yes, I agree we're in good shape for a first iteration. User-define ops can come in a later iteration.
